general:
    eventlogger: 127.0.0.1:7197
    dc_files:
        - ../otp.dc
        - ../toon.dc

messagedirector:
    bind: 127.0.0.1:7199

uberdogs:
    - class: CentralLogger
      id: 4688
      anonymous: false

    - class: ClientServicesManager
      id: 4665
      anonymous: true
      
    - class: DistributedDeliveryManager
      id: 4683
      anonymous: false
      
    - class: ChatAgent
      id: 4681
      anonymous: false
      
    - class: TTSpeedchatRelay
      id: 4712
      anonymous: false

roles:
    - type: clientagent
      bind: 0.0.0.0:6667
      # The client must be kept in-sync with this
      version: sv-1.0.0
      client:
       relocate: true
       add_interest: enabled
      channels:
        min: 1000000000
        max: 1009999999

    - type: stateserver
      control: 10000

    - type: database
      control: 4003
      generate:
        min: 100000000
        max: 399999999
      backend:
        type: yaml
        foldername: ../database/astrondb

    - type: dbss
      database: 4003
      ranges:
        - min: 100000000
          max: 399999999

    - type: eventlogger
      bind: 127.0.0.1:7197
      output: ../events/events-%y%m%d_%H%M%S.log
